### ISSUE TITLE
New Support

### ISSUE THREAD

**Issue by Danieleeffe1** [yireo/Yireo_Webp#16]
Good morning

There is a community that is carrying forward Magento 1 with the new name of OpenMage.

We are looking for developers who don't want to throw away years of work done with Magento 1

Please take a look at the project and consider reopening support for your work

Thank you

**Comment by jissereitsma** [comment]
Thanks, but no thanks. Any developer is free to make choices, and my choice is that I'm not able to maintain Magento 1 modules partially because I have not worked with Magento 1 anymore for years. The packages might work, but if not, other people need to volunteer for maintaining this.
