### ISSUE TITLE
Composer ErrorException on non-existing Template

### ISSUE THREAD

**Issue by kkrieger85** [yireo/Yireo_Webp#2]
https://github.com/yireo/Yireo_Webp/blob/3b9c0985b2400bb2a367165c0bfada92ea44297f/modman#L4

```
Package operations: 1 install, 0 updates, 0 removals
  - Installing yireo/magento1-webp (1.0.5): Downloading (100%)
Writing lock file
Generating autoload files


  [ErrorException]
  Source /var/www/vhosts/mygento.org/httpdocs/vendor/yireo/magento1-webp/source/app/design/frontend/base/default/templates/webp does not exi
```

**Comment by jissereitsma** [comment]
The `templates` were removed some time ago, but the `modman` file did not reflect this yet. Fixed in commit https://github.com/yireo/Yireo_Webp/commit/0e1817ac663c5b955896326df9d6ec01d06f54ac
