### ISSUE TITLE
Feature Request: Configuration to enable/disable module

### ISSUE THREAD

**Issue by duckchip** [yireo/Yireo_Webp#8]
Hi there! 

Would it be possible to add a configuration option to enable/disable this module? 
We use this module in combination with other optimisation techniques and the option to enable or disable integration of WEBP images would be handy :)

Thx in advance!

Tristan

**Comment by jissereitsma** [comment]
Isn't the "Disable Modules Output"  feature of the Magento core already good enough? https://github.com/yireo/Yireo_Webp/blob/master/source/app/code/community/Yireo/Webp/Helper/Data.php#L132

**Comment by duckchip** [comment]
Gonna close this issue since it is meant for the M2 module, my bad
